{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "insighthub.fullname" . }}-default
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - podSelector: {}
    {{- if .Values.observability.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.observability.serviceMonitor.prometheusNamespace | quote }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
    {{- end }}
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
{{- end }}
