{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "insighthub.fullname" . }}-secrets
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretsStore.provider }}
  secretObjects:
    - secretName: {{ .Values.secretsStore.secretName }}
      type: Opaque
      data:
        {{- range .Values.secretsStore.keys }}
        - objectName: {{ . | quote }}
          key: {{ . | quote }}
        {{- end }}
  parameters:
    region: {{ .Values.secretsStore.awsRegion | quote }}
    objects: |
      - objectName: "{{ .Values.secretsStore.awsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .Values.secretsStore.keys }}
          - path: {{ . | quote }}
            objectAlias: {{ . | quote }}
          {{- end }}
{{- end }}
