{{- if .Values.serviceAccounts.web.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insighthub.webServiceAccountName" . }}
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccounts.web.annotations | nindent 4 }}
{{- end }}
{{- if .Values.serviceAccounts.api.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insighthub.apiServiceAccountName" . }}
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    {{- toYaml .Values.serviceAccounts.api.annotations | nindent 4 }}
{{- end }}
{{- if .Values.serviceAccounts.worker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insighthub.workerServiceAccountName" . }}
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion-worker
  annotations:
    {{- toYaml .Values.serviceAccounts.worker.annotations | nindent 4 }}
{{- end }}
